### ISSUE TITLE
Doesn't work at all in Arch Linux

### ISSUE THREAD

**Issue by n1trux** [benjypng/firefox-extension-logseq-quickcapture#11]
The callback URL gets shown, the window gets activated but there's nothing added in Logseq v0.9.4 https://github.com/logseq/logseq/commit/1067ffd

I have set the site where it needs to be added to TODAY. But with the other suggestions (e.g. `cursor`) it doesn't work either.

Installed Logseq-bin from the AUR and using this in KDE.

**Comment by vibl** [comment]
It doesn't work in Kubuntu 22.04 either (Logseq 0.9.4). Installed with appimage.

**Comment by roaroid** [comment]
Trying quick capture doesn't also work here in Arch Linux using Chromium and latest Logseq.

The message i get is *Creation of the input/output module not possible. Unknown protocol "logseq"* from KIOExec.
Logseq-bin was also installed from AUR, KDE is used.

However `~/.config/mimeapps.list` seems to contain the logseq-protocol handler:

```
x-scheme-handler/logseq=logseq-desktop.desktop
```

The file logseq-desktop.desktop also exists in `/usr/share/applications/`

Any ideas?

**Comment by martinusus** [comment]
Does not work in OpenSuse Tumbleweed as well. Seems it does not work at any linux. It would be good to mention it in the description.

**Comment by ahangarha** [comment]
A related issue on logseq https://github.com/logseq/logseq/issues/9999

**Comment by loziniak** [comment]
[Should be fixed](https://aur.archlinux.org/cgit/aur.git/commit/?h=logseq-desktop-bin&id=bf9f782c8d9b21172b89a21cb5c462ed875df70f) in Arch/Manjaro AUR  `logseq-desktop-bin` package. There was [an issue](https://github.com/logseq/logseq/issues/6185#issuecomment-1197996764) with the package's `.desktop` file.

**Comment by benjypng** [comment]
Should be fixed in the latest version.
