### ISSUE TITLE
Ability to configure the tag/namespace for the captured content in Logseq

### ISSUE THREAD

**Issue by dklawren** [benjypng/firefox-extension-logseq-quickcapture#12]
Currently all captured information is tagged in Logseq with [[quick capture]]. It would be nice to be able to configure the tag in the Firefox extension preferences to be something different than the default. For example, I use the todoist plugin for Logseq (thanks for that one as well!) to pull in Inbox items from my Todoist. And they are tagged [[Inbox]]. If my captures from Firefox were also able to use that tag as well I can see all of my captures in once page. I manually change the [[quick capture]] to [[Inbox]] now.

Thanks!

**Comment by benjypng** [comment]
Hi, this setting can be configured in Logseq's config.edn​.
________________________________
From: David Lawrence ***@***.***>
Sent: Tuesday, June 6, 2023 3:53 AM
To: hkgnp/firefox-extension-logseq-quickcapture ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hkgnp/firefox-extension-logseq-quickcapture] Ability to configure the tag/namespace for the captured content in Logseq (Issue #12)


Currently all captured information is tagged in Logseq with [[quick capture]]. It would be nice to be able to configure the tag in the Firefox extension preferences to be something different than the default. For example, I use the todoist plugin for Logseq (thanks for that one as well!) to pull in Inbox items from my Todoist. And they are tagged [[Inbox]]. If my captures from Firefox were also able to use that tag as well I can see all of my captures in once page. I manually change the [[quick capture]] to [[Inbox]] now.

Thanks!

**Comment by dklawren** [comment]
Ah thanks. Learned something new.
