### ISSUE TITLE
Only works once logseq is running

### ISSUE THREAD

**Issue by MikiDi** [benjypng/firefox-extension-logseq-quickcapture#16]
When I use the plugin when Logseq isn't running, it opens Logseq, but fails to add the quickcapture. Once Logseq is open, repeating the same action, the quickcapture dóes register.

My desktop launcher looks as follows:
```
[Desktop Entry]
Name=Logseq
Exec=/opt/Logseq-linux-x64-0.9.19.AppImage %u
Terminal=false
Type=Application
Icon=gnome-panel-launcher
Comment=
MimeType=x-scheme-handler/logseq;text/html;
```

Running Fedora 37, Gnome 43.8, Logseq 0.9.19, Firefox 117.0.1

**Comment by ivan-danilov** [comment]
@MikiDi as mentioned [here](https://github.com/logseq/logseq/issues/5942#issuecomment-1176480446) it is a logseq limitation. Not sure if the information is still current, though. Regardless, it has nothing to do with this plugin.

**Comment by benjypng** [comment]
Fixed in the latest version.
