### ISSUE TITLE
Does not work on some pages.

### ISSUE THREAD

**Issue by loziniak** [benjypng/firefox-extension-logseq-quickcapture#17]
A small empty notice "bubble" is displayed, and `logseq://x-callback-url` link is not created / executed.

For example:
https://beinternetawesome.withgoogle.com/pl_all/interland

Screenshot of the behavior:
![obraz](https://github.com/hkgnp/firefox-extension-logseq-quickcapture/assets/5331492/d71d42f6-2db0-4d20-921e-8540c2ab0a1f)

**Comment by ivan-danilov** [comment]
I noticed that it does not work consistently when the title contains `#`, which makes me think it has something to do with character escaping in `logseq://` URL. In the example above there's no `#` but might be something similar?

**Comment by djm2k** [comment]
I am running into this with two different errors in the console on different pages:
- https://extensionworkshop.com/documentation/develop/debugging/
(trying to Quick Capture a few times will work eventually, race condition?)
    ```javascript
  Uncaught (in promise) Error: Selection.getRangeAt: 0 is out of range undefined
      //<anonymous> moz-extension://34b7ba4e-ffd5-4cba-93b4-80519489d5c3/src/script.js:7
      //AsyncFunctionThrow self-hosted:808
      //(Async: async)
      //<anonymous> moz-extension://34b7ba4e-ffd5-4cba-93b4-80519489d5c3/src/script.js:26
  ```

- https://pages.lip6.fr/Marc.Shapiro/papers/rgasplit-group2016-11.pdf
(Will never work)
  ```javascript
  Uncaught (in promise) Error: Missing host permission for the tab undefined
      //<anonymous> moz-extension://34b7ba4e-ffd5-4cba-93b4-80519489d5c3/src/script.js:7
      //AsyncFunctionThrow self-hosted:808
      //(Async: async)
      //<anonymous> moz-extension://34b7ba4e-ffd5-4cba-93b4-80519489d5c3/src/script.js:26
  ```

**Comment by benjypng** [comment]
> I am running into this with two different errors in the console on different pages:
> 
>     * https://extensionworkshop.com/documentation/develop/debugging/
>       (trying to Quick Capture a few times will work eventually, race condition?)
>       ```js
>       Uncaught (in promise) Error: Selection.getRangeAt: 0 is out of range undefined
>         //<anonymous> moz-extension://34b7ba4e-ffd5-4cba-93b4-80519489d5c3/src/script.js:7
>         //AsyncFunctionThrow self-hosted:808
>         //(Async: async)
>         //<anonymous> moz-extension://34b7ba4e-ffd5-4cba-93b4-80519489d5c3/src/script.js:26
>       ```

This should be fixed in the latest version.

>     * https://pages.lip6.fr/Marc.Shapiro/papers/rgasplit-group2016-11.pdf
>       (Will never work)
>       ```js
>       Uncaught (in promise) Error: Missing host permission for the tab undefined
>           //<anonymous> moz-extension://34b7ba4e-ffd5-4cba-93b4-80519489d5c3/src/script.js:7
>           //AsyncFunctionThrow self-hosted:808
>           //(Async: async)
>           //<anonymous> moz-extension://34b7ba4e-ffd5-4cba-93b4-80519489d5c3/src/script.js:26
>       ```

The extension does not work for PDFs. You may want to use Zotero or Readwise to handle PDFs in browser.
