### ISSUE TITLE
How to modify the [[quick capture]] description?

### ISSUE THREAD

**Issue by maikol-solis** [benjypng/firefox-extension-logseq-quickcapture#18]
Hi, it's basically the title. 

The template for each capture is fixed to 

```
** <Time> ** [[quick capture]]:  [[Link][Title]]
```

I would like to know if it's possible to change the `[[quick capture]]` part with a meaningful description for my to-do list.

Best.

**Comment by ivan-danilov** [comment]
@maikol-solis this plugin only sends information to the open logseq instance through custom URL Scheme. The handling itself is performed by logseq, and there's section in config.edn to define templates for quick captures.

I didn't want `[[quick capture]]` too, so I modified mine as follows:
```
 :quick-capture-templates
 {:text "{time}: {url}"
  :media "[[quick capture]] **{time}**: {url}"}
```

**Comment by maikol-solis** [comment]
Thanks. 
This is the information that I was looking for. 
Best.
