### ISSUE TITLE
Keyboard Shortcut?

### ISSUE THREAD

**Issue by AlJohri** [benjypng/firefox-extension-logseq-quickcapture#2]
Thanks for the amazing plugin! Would it be possible to expose this functionality via a customizable keyboard shortcut?

**Comment by benjypng** [comment]
Hi! Please refer here on how to do it: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

**Comment by srustamo** [comment]
@benjypng the reference url you linked works only for those extensions, which make the shortcut command available. Such commands then can be assigned a shortcut.
