### ISSUE TITLE
Version 0.2.6 is too big

### ISSUE THREAD

**Issue by queeup** [benjypng/firefox-extension-logseq-quickcapture#20]
Hi,

Version `0.2.4` is `28.32 KB`
Version `0.2.6` is `11.19 MB`

Do you really need `screenshot` directory on the extension xpi?

![Ekran Görüntüsü - 2024-08-23 23-31-29](https://github.com/user-attachments/assets/53d848d3-372c-4fac-b85e-c03789961d2f)

**Comment by benjypng** [comment]
Thanks for surfacing this!

Fixed in 0.2.7 when Firefox approves it for the marketplace.
