### ISSUE TITLE
New version is not on Mozilla Addons page

### ISSUE THREAD

**Issue by loziniak** [benjypng/firefox-extension-logseq-quickcapture#21]
There is still version `0.2.4` present instead `0.2.5` (#15). Maybe this is not happening automatically? Some action is required from @benjypng ?

**Comment by benjypng** [comment]
https://addons.mozilla.org/en-US/firefox/addon/logseq-quick-capture-v2/ 

Use this link?

**Comment by loziniak** [comment]
Oh, and there is even `0.2.8`! Perhaps the problem is, that in Mozilla page the address of the repo is still `hkgnp/firefox-extension-logseq-quickcapture`?

**Comment by loziniak** [comment]
Thank you.

**Comment by benjypng** [comment]
Unfortunately as mentioned in the description, I lost access to that account.

**Comment by mwesten** [comment]
Please update the URL in this readme-file to the new URL on the Addon-store (https://addons.mozilla.org/nl/firefox/addon/logseq-quick-capture-v2/) and add more / the same information to the mozilla page as is on the old one. Also link from there to this Github.
I was very cautious for a duplicate in the addon-store.
