### ISSUE TITLE
New tab is closing too fast

### ISSUE THREAD

**Issue by loziniak** [benjypng/firefox-extension-logseq-quickcapture#22]
When using the plugin for the first time, the tab that the plugin opens asks for a permission for a plugin to open `logseq://` links. The tab closes so fast, that agreeing for this and clicking the confirmation button is almost impossible.

**Comment by benjypng** [comment]
Fixed in 0.2.9. It is currently under review.

**Comment by loziniak** [comment]
Thank you!

(ref: 261293a)
