### ISSUE TITLE
README and Firefox Extension Description Update

### ISSUE THREAD

**Issue by AlJohri** [benjypng/firefox-extension-logseq-quickcapture#3]
Would it be possible to link the extension in the repo's README and link the repo in the extension's description?

https://addons.mozilla.org/en-US/firefox/addon/logseq-quick-capture/

**Comment by benjypng** [comment]
Ok, have done so.

**Comment by AlJohri** [comment]
@hkgnp thanks! I think it would be helpful to link to the github repository from the firefox addon page as well so its easier to trust this extension. lots of malicious extensions out there these days :) 

![Screen Shot 2022-12-13 at 8 29 32 AM](https://user-images.githubusercontent.com/2790092/207333949-f27a380e-35a0-4902-9c07-808862678f46.png)

as far as I can tell, currently there's no backlink to the repo and requires googling to find

**Comment by benjypng** [comment]
I see! [Have done so!](https://addons.mozilla.org/en-GB/firefox/addon/logseq-quick-capture/)
