### ISSUE TITLE
Missing URL Query Parameters

### ISSUE THREAD

**Issue by AlJohri** [benjypng/firefox-extension-logseq-quickcapture#4]
For any URL with more than 1 query parameter, it looks like this extension skips all query parameters after the first (starting with `&key=value`).

For example, in this URL: https://www.google.com/search?client=firefox-b-1-e&q=stopwords+that+sometimes+have+meaning

If I select the first snippet and then click on the extension, I get the following output:

```
**08:19** [[quick capture]]: The general strategy for determining a stop list is to _sort the terms by collection frequency_ (the total number of times each term appears in the document ... [stopwords that sometimes have meaning - Google Search](https://www.google.com/search?client=firefox-b-1-e)
```

As you can see, the first query parameter (`?client=firefox-b-1-e`) is retained while the remaining parameter (`&q=stopwords+that+sometimes+have+meaning`) is left out.

I am using Firefox Extended Support Release (ESR) version 102.5.0esr (64-bit) on macOS 12.3.1.

**Comment by benjypng** [comment]
Please try the latest version from the Firefox store.

**Comment by AlJohri** [comment]
It works, thank you for the quick fix!
