### ISSUE TITLE
`undefined` values in quickCapture url

### ISSUE THREAD

**Issue by alx** [benjypng/firefox-extension-logseq-quickcapture#6]
Hi @hkgnp 

Thanks for your extension, it works well, until it's not, I'm trying to know why.

It appears that some variable are undefined after 'something' happens, `page` and `append` values are built at following line:

https://github.com/hkgnp/firefox-extension-logseq-quickcapture/blob/4a843b47460b03f885ede49bb198f885ab62acd4/src/script.js#L11

console output:

```
13:19:39.676 › open-url {:url "logseq://x-callback-url/quickCapture?page=TODAY&append=true&title=Tweet%20/%20Twitter&content=&url=https%3A%2F%2Ftwitter.com%2Fjakluge%2Fstatus%2F1607683259961573377"}
13:21:04.749 › open-url {:url "logseq://x-callback-url/quickCapture?page=undefined&append=undefined&title=Add-ons%20Manager&content=&url=about%3Aaddons"}
13:22:56.711 › open-url {:url "logseq://x-callback-url/quickCapture?page=undefined&append=undefined&title=Kris%20Kashtanova%20on%20Twitter:%20%22My%20prompt:%20in%20a%20style%20of%201990s%20point%20and%20click%2016bit%20adventure%20game%20Stranger%20Things%20--ar%203:2%20--v%204%20Would%20love%20your%20fav%20movies%20and%20shows%20as%20old%20games%20https://t.co/PY2Pst2pyv%22%20/%20Twitter&content=My%20prompt:%20in%20a%20style%20of%201990s%20point%20and%20click%2016bit%20adventure%20game%20Stranger%20Things%20--ar%203:2%20--v%204&url=https%3A%2F%2Ftwitter.com%2Ficreatelife%2Fstatus%2F1607555335664844801"}
```

Could you have a look?

Thanks and have a nice day,

Alex

**Comment by benjypng** [comment]
Could you take a screenshot of your options page please?

**Comment by alx** [comment]
Here is the screenshot, I havnt modified the default settings.

![image](https://user-images.githubusercontent.com/373/210177251-a3a0d000-d453-4708-a96c-df7bc6c8b361.png)

**Comment by alx** [comment]
I've tried to disable all other extensions to see if something else was messing up with the async browser call, but it didn't change anything.

**Comment by benjypng** [comment]
Could you try changing `today` to `TODAY`?

**Comment by benjypng** [comment]
Changing to `TODAY` fixes the issue.
