### ISSUE TITLE
Logseq capture extension not working with latest Firefox nightly 

### ISSUE THREAD

**Issue by dklawren** [benjypng/firefox-extension-logseq-quickcapture#7]
I have both current release 109 and nightly 111 of Firefox installed with both having the logseq capture extension installed. I have Logseq itself up and running. And I have both instances of Firefox configured the same. Append the current site to TODAY at the end of the page.  The release version works fine but the nightly version does nothing when I click on the logseq capture button on the toolbar. One note to add is that if I type the full URL in the nightly address bar, the entry is created properly in the Logseq app. For example using `logseq://x-callback-url/quickCapture?page=TODAY&append=true&title=Tweet%20/%20Twitter&content=&url=https%3A%2F%2Ftwitter.com%2Fjakluge%2Fstatus%2F1607683259961573377"` does the right thing. Just not when I hit the logseq button in nightly. Any ideas on how to debug this issue or what the cause might be?

![image](https://user-images.githubusercontent.com/826315/217612251-91a1ebab-d10d-4e41-b737-bf3d87426298.png)

**Comment by abdgad** [comment]
The same issue exists in Firefox 110.0 , the previous version 109 was working fine.
@hkgnp can you please investigate the issue?

**Comment by dklawren** [comment]
> The same issue exists in Firefox 110.0 , the previous version 109 was working fine. @hkgnp can you please investigate the issue?

Definitely something changed from 110 and up.

**Comment by benjypng** [comment]
I've implemented the fix. Looks like some methods have changed in the latest version. Please try 0.2.2 when it is out in the market. It is currently pending review.

**Comment by dklawren** [comment]
Thank you!

**Comment by dklawren** [comment]
Closing as the button is fixed on latest nightly.
