### ISSUE TITLE
Unable to capture on Firefox 110+ after latest extension update

### ISSUE THREAD

**Issue by dklawren** [benjypng/firefox-extension-logseq-quickcapture#8]
When using the latest version of the extension which was recently updated to work with Firefox 110+, I am not able to properly capture anything to Logseq. When clicking the button on a page which I want to capture, the extension opens a new tab where I see a conformation dialog to open asking if it is OK to open the link using Logseq. Before I can do anything, the dialog disappears and the tab closes itself. Sometimes, not always, I can click the open link button fast enough and I will get the capture properly created in Logseq. But it takes multiple tries.Would it be possible to do away with the timeout and close the tab only after the dialog has been confirmed?

OS: Linux 
Firefox: Nightly 112.0a1

**Comment by benjypng** [comment]
I have made the rectification. But I am unable to upload it to the firefox
developer console.
If you need to, you can download it directly from Github?

**Comment by dklawren** [comment]
> I have made the rectification. But I am unable to upload it to the firefox developer console. If you need to, you can download it directly from Github?

I am using the previous iteration of this fix for a bit and is working fine. I was not able to use the xpi in the github repo as it would generate errors when I try to push the button. And also the icon would not display. Not sure what I am doing wrong.

Were you able to figure out why you cannot upload the new version to the Addons console? I would rather download the new version directly from there if possible.

**Comment by hkgnp** [comment]
The new version should be uploaded already!Regards,ben On 4 Mar 2023, at 6:27 AM, David Lawrence ***@***.***> wrote:﻿

I have made the rectification. But I am unable to upload it to the firefox developer console. If you need to, you can download it directly from Github?

I am using the previous iteration of this fix for a bit and is working fine. I was not able to use the xpi in the github repo as it would generate errors when I try to push the button. And also the icon would not display. Not sure what I am doing wrong.
Were you able to figure out why you cannot upload the new version to the Addons console? I would rather download the new version directly from there if possible.

**Comment by benjypng** [comment]
Fixed.
