### ISSUE TITLE
Feature Request: Change "quick capture" label

### ISSUE THREAD

**Issue by johannes1984** [benjypng/firefox-extension-logseq-quickcapture#9]
It would be great to be able to freely change the name of the quick capture label. 

Besides this, when you hover over the icon in Firefox, it says Beastify. Not sure if this is intended.

Thanks a lot for this nice extension :-)

**Comment by benjypng** [comment]
Hi!

The `quickCapture` label can be changed from within `config.edn`.

I've also made the change to the description upon hover. Will be available in `0.2.4` when Firefox publishes it!
